
# which attack to run
attack: lc

# dataset / model choices
dataset: CIFAR10
model: ResNet18
scenario: from_scratch

# data paths
dataset_dir: src/data/
clean_model_path: ./src/saved_models/resnet18_200_clean.pth
saved_models_path: ./src/saved_models/
results_path: ./src/results/
prov_path: ./src/Training_Prov_Data/
exp: 

# training schedule
epochs: 200
ep_bl: 10
ep_bl_base: 200
ep_sl: 10
ep_sl_base: 200

# batch sizes
bs: 128
bs_bl: 128
bs_sl: 128

# attack parameters
target_class: 2
source_class: 0
pr_tgt: 10
pr_sus: 50
eps: 16
vis: 255

# which phases to run
batch_level: true
clean_training: false
poisoned_training: true
sample_level: true
score_samples: true
retrain: true
get_result: false
force: false

# misc
gpu_id: 0
global_seed: 545
lr: 0.1
opt: sgd
training_mode: true
sample_from_test: false
cv_model: RandomForest
groups: 5
threshold: 0.5
random: false
