
# which attack to run
attack: sa 

# dataset / model choices 
dataset: slt10 
model: ViT 
scenario: fine_tuning 
 
# data paths
dataset_dir: src/data/ 
clean_model_path: ./src/saved_models/model_sa_vit_10_64.pth 
saved_models_path: ./src/saved_models/
results_path: ./src/results/
prov_path: ./src/Training_Prov_Data/
exp: 

# training schedule
epochs: 10
ep_bl: 5
ep_bl_base: 0
ep_sl: 25
ep_sl_base: 0


# batch sizes
bs: 64
bs_bl: 64
bs_sl: 64

# attack parameters
target_class: 1
source_class: 0
pr_tgt: 50
pr_sus: 50
eps: 16
vis: 255

# which phases to run
batch_level: true
clean_training: false
poisoned_training: true
sample_level: true
score_samples: true
retrain: true
get_result: false
force: false

# misc
gpu_id: 1
global_seed: 545
lr: 0.0001
opt: adam
training_mode: false
sample_from_test: true
cv_model: RandomForest
groups: 5
custom_threshold: 0.5 
threshold_type: gaussian 
k_1: 1
k_2: 0.0001 
random: false
