
# which attack to run
attack: ht 

# dataset / model choices 
dataset: imagenet 
model: CustomResNet18 
scenario: fine_tuning 
 
# data paths
dataset_dir: src/data/ 
clean_model_path: ./src/saved_models/custom_resnet18_tinyimagenet_100_4.pth 
saved_models_path: ./src/saved_models/
results_path: ./src/results/
prov_path: ./src/Training_Prov_Data/
exp: 

# training schedule
epochs: 5
ep_bl: 1
ep_bl_base: 0
ep_sl: 25
ep_sl_base: 0



# batch sizes
bs: 64
bs_bl: 64
bs_sl: 64

# attack parameters
target_class: 40
source_class: 30
pr_tgt: 50
pr_sus: 50
eps: 16
vis: 255

# which phases to run
batch_level: true
clean_training: false
poisoned_training: false
sample_level: true
score_samples: true
retrain: true
get_result: false
force: false

# misc
gpu_id: 0
global_seed: 545
lr: 0.001
opt: adam 
training_mode: false
sample_from_test: true
cv_model: RandomForest 
groups: 5
custom_threshold: 0.5 
threshold_type: gaussian 
k_1: 40
k_2: 0.0001 
random: false
